### ISSUE TITLE
Can't set marker 

### ISSUE THREAD

**Issue by Raist-dlt** [iotaledger/ec.ixi#4]
After the transfer, I can't set a marker for the ingoing hash. After referencing the outgoing hash, I can use the ingoing as well. I'm not sure if this is normal behaviour.

**Comment by Thoralf-M** [comment]
With `ingoing hash` he meant the tail transaction, it's also not possible to reference both transactions at once, you have to reference the index 1 transaction first (that works even if you have 3 transactions in the bundle)

**Comment by vuapo-eth** [comment]
fixed in https://github.com/iotaledger/ec.ixi/commit/25d28791f3c1a5ec36fb63b0d56a4899cd54b5ca
